### ISSUE TITLE
Unable to mount  volume for logs dir 

### ISSUE THREAD

**Issue by rjdp** [ozangunalp/kafka-native#170]
following is my `docker-compose` file

```
version: '3.5'

name: kafka-native
services:
  broker1:
    image: quay.io/ogunalp/kafka-native:latest
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      SERVER_HOST: broker1
      KAFKA_BROKER_ID: 1
      SERVER_CLUSTER_ID: BmMQZPq6Qoua1-yvgGJFbA
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:9094
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka-data-one:/tmp/kraft-combined-logs
    networks:
      - kafka-network
 
networks:
  kafka-network:
    name: kafka-native

volumes:
  kafka-data-one:


```

Following are crash logs:

```
broker1-1  | __  ____  __  _____   ___  __ ____  ______ 
broker1-1  |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
broker1-1  |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
broker1-1  | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
broker1-1  | 2024-04-26 21:26:47,313 INFO  [com.oza.kaf.ser.EmbeddedKafkaBroker] (main) auto-configuring server
broker1-1  | metaPropertiesEnsemble=MetaPropertiesEnsemble(metadataLogDir=Optional.empty, dirs={/tmp/kraft-combined-logs: EMPTY})
broker1-1  | 2024-04-26 21:26:47,314 INFO  [com.oza.kaf.ser.Storage] (main) Formatting /tmp/kraft-combined-logs with metadata.version 3.3-IV0.
broker1-1  | 2024-04-26 21:26:47,317 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
broker1-1  |    at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
broker1-1  |    at io.quarkus.runtime.Application.start(Application.java:101)
broker1-1  |    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
broker1-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
broker1-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
broker1-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
broker1-1  |    at io.quarkus.runner.GeneratedMain.main(Unknown Source)
broker1-1  | Caused by: kafka.tools.TerseFailure: Error while writing meta.properties file /tmp/kraft-combined-logs: /tmp/kraft-combined-logs/bootstrap.checkpoint.tmp
broker1-1  |    at kafka.tools.StorageTool$.$anonfun$formatCommand$4(StorageTool.scala:460)
broker1-1  |    at org.apache.kafka.metadata.properties.MetaPropertiesEnsemble$Copier.writeLogDirChanges(MetaPropertiesEnsemble.java:379)
broker1-1  |    at kafka.tools.StorageTool$.$anonfun$formatCommand$2(StorageTool.scala:462)
broker1-1  |    at java.base@17.0.10/java.lang.Iterable.forEach(Iterable.java:75)
broker1-1  |    at java.base@17.0.10/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
broker1-1  |    at kafka.tools.StorageTool$.formatCommand(StorageTool.scala:449)
broker1-1  |    at kafka.tools.StorageTool$.formatCommand(StorageTool.scala:415)
broker1-1  |    at kafka.tools.StorageTool.formatCommand(StorageTool.scala)
broker1-1  |    at com.ozangunalp.kafka.server.Storage.formatStorageFromConfig(Storage.java:56)
broker1-1  |    at com.ozangunalp.kafka.server.EmbeddedKafkaBroker.start(EmbeddedKafkaBroker.java:205)
broker1-1  |    at com.ozangunalp.kafka.server.Startup.startup(Startup.java:37)
broker1-1  |    at com.ozangunalp.kafka.server.Startup_Observer_startup_lDxI_XYb49w9c3LH146P8PmORkk.notify(Unknown Source)
broker1-1  |    at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
broker1-1  |    at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
broker1-1  |    at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
broker1-1  |    at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
broker1-1  |    at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
broker1-1  |    at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
broker1-1  |    at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
broker1-1  |    ... 7 more
broker1-1  | 
broker1-1 exited with code 1

```
