### ISSUE TITLE
Docker compose health checks

### ISSUE THREAD

**Issue by rupurt** [ozangunalp/kafka-native#216]
Howdy,

Thanks so much for building `kafka-native`. It feels super awesome to have a fast local development loop with Kafka.

Do you have a recommendation on how to do health checks in docker compose? I don't see any examples in the docker compose file within this repo and utilities from other images don't appear to be available e.g.

```yaml
    healthcheck:
      test: /kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092 || exit 1
      interval: 10s
      timeout: 10s
      retries: 60
      start_period: 30s
```
